# tomcat
server:
  port: 8002
spring:
  application:
    name: mango-backup
  boot:
    admin:
      client:
        url: "http://localhost:8000"
        
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: 123a123b
      database: mango
      
management:
  endpoints:
    web:
      exposure:
        include: "*"